#!/bin/sh
#
export APP_SERVER_CONTROLLER_HOME=/ArvueAppServerController/src

# See how we were called.
case "$1" in
  start)
  cd $APP_SERVER_CONTROLLER_HOME
  nohup python AppServerController.py 2>/dev/null &
  echo
  ;;
  stop)
  for proc_id in `ps -ef|grep AppServerController|grep -v grep|grep -v init.d|sed  's/  */ /g'| cut -d' ' -f2`
  do
	kill -9 $proc_id
  done
  echo
  ;;
  status)
  proc_size=`ps -ef|grep AppServerController|grep -v grep|grep -v init.d|wc -l`
  echo $proc_size
  ;;
  restart)
  $0 stop
  sleep 2
  $0 start
  ;;
  *)
  echo "Usage: $0 {start|stop|restart}"
  exit 1
esac
exit 0